#ifndef GUARD_CONSTANTS_MAP_EVENT_IDS_H
#define GUARD_CONSTANTS_MAP_EVENT_IDS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/*/map.json
//

// MAP_ALLERGY_LADY_HOUSE
#define MS_D 1

// MAP_ALLERGY_LADY_UPSTAIRS
#define CLARICE 1

// MAP_BRAMBLEWOOD_TOWN
#define WILLOW 1

// MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F
#define LOCALID_PLAYERS_HOUSE_1F_MOM 1
#define LOCALID_RIVALS_HOUSE_1F_MOM 4
#define LOCALID_PLAYERS_HOUSE_1F_DAD 5
#define LOCALID_RIVALS_HOUSE_1F_RIVAL 7

// MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F
#define LOCALID_RIVALS_HOUSE_2F_RIVAL 1
#define LOCALID_PLAYERS_HOUSE_2F_MOM 14

// MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F
#define LOCALID_PLAYERS_HOUSE_1F_MOM 1
#define LOCALID_RIVALS_HOUSE_1F_MOM 4
#define LOCALID_PLAYERS_HOUSE_1F_DAD 5
#define LOCALID_RIVALS_HOUSE_1F_RIVAL 7

// MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F
#define LOCALID_RIVALS_HOUSE_2F_RIVAL 1
#define LOCALID_PLAYERS_HOUSE_2F_MOM 14

// MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB
#define LOCALID_BIRCHS_LAB_AIDE 1
#define LOCALID_DOC_A_LAB 2
#define LOCALID_DOC_B_LAB 3
#define LOCALID_BEA_LAB 4

// MAP_PEBBLE_PERSON
#define PEBBLE_MANIAC 1

// MAP_ROUTE1000
#define bea 1

// MAP_ROUTE109
#define LOCALID_DOC_A 1
#define LOCALID_BEA_DOCK 2
#define LOCALID_CAPTAIN_DOCK 3
#define LOCALID_DOC_B 4

// MAP_SSENNA_DECK
#define LOCALID_ENNA_BEA 1
#define LOCALID_ENNA_CAPTAIN 2

#endif // GUARD_CONSTANTS_MAP_EVENT_IDS_H
