# 1 "data/maps/Route999/scripts.pory"

# 2 "data/maps/Route999/scripts.pory"
Route999_MapScripts::
# 3 "data/maps/Route999/scripts.pory"
	.byte 0
# 4 "data/maps/Route999/scripts.pory"

# 5 "data/maps/Route999/scripts.pory"
Route999_EventScript_Sign1::
# 6 "data/maps/Route999/scripts.pory"
	msgbox Route999_Text_Sign1, MSGBOX_SIGN
# 7 "data/maps/Route999/scripts.pory"
	end
# 8 "data/maps/Route999/scripts.pory"

# 9 "data/maps/Route999/scripts.pory"
Route999_Text_Sign1::
# 10 "data/maps/Route999/scripts.pory"
    .string "Thank you for playing the demo!$"
